<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\VerificationController;
use App\Http\Controllers\TemplateController;
use App\Http\Controllers\BalitaController;
use App\Http\Controllers\StuntingController;
use App\Http\Controllers\IbuHamilController;
use App\Http\Controllers\IbuNifasController;
use App\Http\Controllers\IbuMenyusuiController;
use App\Http\Controllers\RemajaPutriController;
use App\Http\Controllers\GentingController;
use App\Http\Controllers\AksiKonvergensiController;
use App\Http\Controllers\PetaGeospasialController;
use App\Http\Controllers\PendampingKeluargaController;
use App\Http\Controllers\CarouselController;
use App\Http\Controllers\DataRisetController;
use App\Http\Controllers\TentangKamiController;
use App\Http\Controllers\LayananKamiController;
use App\Http\Controllers\GaleriProgramController;
use App\Http\Controllers\PublikasiController;
use App\Http\Controllers\ReferensiController;
use App\Http\Controllers\DataMonitoringController;
use App\Http\Controllers\DataPendudukController;
use App\Http\Controllers\KartuKeluargaController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\KelurahanController;
use App\Http\Controllers\IbuController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/login', [AuthController::class, 'showLoginForm'])->name('login');
Route::post('/login', [AuthController::class, 'login']);
Route::post('/logout', [AuthController::class, 'logout'])->name('logout');

Route::get('/register', [AuthController::class, 'showRegisterForm'])->name('register');
Route::post('/register', [AuthController::class, 'register']);
Route::get('/download-template', [AuthController::class, 'downloadTemplate'])->name('download.template');

Route::middleware('auth')->group(function () {
    Route::get('/dashboard', [AuthController::class, 'dashboard'])->name('dashboard');
    Route::middleware('role:master')->group(function () {
        Route::get('/verifikasi-akun', [VerificationController::class, 'index'])->name('verifikasi.index');
        Route::post('/verifikasi-akun/{id}/approve', [VerificationController::class, 'approve'])->name('verifikasi.approve');
        Route::post('/verifikasi-akun/{id}/reject', [VerificationController::class, 'reject'])->name('verifikasi.reject');
        Route::get('/templates', [TemplateController::class, 'index'])->name('templates.index');
        Route::post('/templates', [TemplateController::class, 'store'])->name('templates.store');
        Route::delete('/templates/{id}', [TemplateController::class, 'destroy'])->name('templates.destroy');
        Route::get('/users', [UserController::class, 'index'])->name('users.index');
        Route::get('/users/{id}/edit', [UserController::class, 'edit'])->name('users.edit');
        Route::put('/users/{id}', [UserController::class, 'update'])->name('users.update');
        Route::delete('/users/{id}', [UserController::class, 'destroy'])->name('users.destroy');
        Route::get('/balita', [BalitaController::class, 'index'])->name('balita.index');
        Route::get('/balita/create', [BalitaController::class, 'create'])->name('balita.create');
        Route::post('/balita', [BalitaController::class, 'store'])->name('balita.store');
        Route::get('/balita/{id}/edit', [BalitaController::class, 'edit'])->name('balita.edit');
        Route::put('/balita/{id}', [BalitaController::class, 'update'])->name('balita.update');
        Route::delete('/balita/{id}', [BalitaController::class, 'destroy'])->name('balita.destroy');
        Route::post('/balita/import', [BalitaController::class, 'import'])->name('balita.import');
        Route::get('/balita/download-template', [BalitaController::class, 'downloadTemplate'])->name('balita.downloadTemplate');
        Route::get('/stunting', [StuntingController::class, 'index'])->name('stunting.index');
        Route::get('/stunting/create', [StuntingController::class, 'create'])->name('stunting.create');
        Route::post('/stunting', [StuntingController::class, 'store'])->name('stunting.store');
        Route::get('/stunting/{id}/edit', [StuntingController::class, 'edit'])->name('stunting.edit');
        Route::put('/stunting/{id}', [StuntingController::class, 'update'])->name('stunting.update');
        Route::delete('/stunting/{id}', [StuntingController::class, 'destroy'])->name('stunting.destroy');
        Route::get('/ibu-hamil', [IbuHamilController::class, 'index'])->name('ibu_hamil.index');
        Route::get('/ibu-hamil/create', [IbuHamilController::class, 'create'])->name('ibu_hamil.create');
        Route::post('/ibu-hamil', [IbuHamilController::class, 'store'])->name('ibu_hamil.store');
        Route::get('/ibu-hamil/{id}/edit', [IbuHamilController::class, 'edit'])->name('ibu_hamil.edit');
        Route::put('/ibu-hamil/{id}', [IbuHamilController::class, 'update'])->name('ibu_hamil.update');
        Route::delete('/ibu-hamil/{id}', [IbuHamilController::class, 'destroy'])->name('ibu_hamil.destroy');
        Route::get('/ibu-nifas', [IbuNifasController::class, 'index'])->name('ibu_nifas.index');
        Route::get('/ibu-nifas/create', [IbuNifasController::class, 'create'])->name('ibu_nifas.create');
        Route::post('/ibu-nifas', [IbuNifasController::class, 'store'])->name('ibu_nifas.store');
        Route::get('/ibu-nifas/{id}/edit', [IbuNifasController::class, 'edit'])->name('ibu_nifas.edit');
        Route::put('/ibu-nifas/{id}', [IbuNifasController::class, 'update'])->name('ibu_nifas.update');
        Route::delete('/ibu-nifas/{id}', [IbuNifasController::class, 'destroy'])->name('ibu_nifas.destroy');
        Route::get('/ibu-menyusui', [IbuMenyusuiController::class, 'index'])->name('ibu_menyusui.index');
        Route::get('/ibu-menyusui/create', [IbuMenyusuiController::class, 'create'])->name('ibu_menyusui.create');
        Route::post('/ibu-menyusui', [IbuMenyusuiController::class, 'store'])->name('ibu_menyusui.store');
        Route::get('/ibu-menyusui/{id}/edit', [IbuMenyusuiController::class, 'edit'])->name('ibu_menyusui.edit');
        Route::put('/ibu-menyusui/{id}', [IbuMenyusuiController::class, 'update'])->name('ibu_menyusui.update');
        Route::delete('/ibu-menyusui/{id}', [IbuMenyusuiController::class, 'destroy'])->name('ibu_menyusui.destroy');
        Route::get('/remaja-putri', [RemajaPutriController::class, 'index'])->name('remaja_putri.index');
        Route::get('/remaja-putri/create', [RemajaPutriController::class, 'create'])->name('remaja_putri.create');
        Route::post('/remaja-putri', [RemajaPutriController::class, 'store'])->name('remaja_putri.store');
        Route::get('/remaja-putri/{id}/edit', [RemajaPutriController::class, 'edit'])->name('remaja_putri.edit');
        Route::put('/remaja-putri/{id}', [RemajaPutriController::class, 'update'])->name('remaja_putri.update');
        Route::delete('/remaja-putri/{id}', [RemajaPutriController::class, 'destroy'])->name('remaja_putri.destroy');
        Route::get('/genting', [GentingController::class, 'index'])->name('genting.index');
        Route::get('/genting/create', [GentingController::class, 'create'])->name('genting.create');
        Route::post('/genting', [GentingController::class, 'store'])->name('genting.store');
        Route::get('/genting/{id}/edit', [GentingController::class, 'edit'])->name('genting.edit');
        Route::put('/genting/{id}', [GentingController::class, 'update'])->name('genting.update');
        Route::delete('/genting/{id}', [GentingController::class, 'destroy'])->name('genting.destroy');
        Route::get('/aksi-konvergensi', [AksiKonvergensiController::class, 'index'])->name('aksi_konvergensi.index');
        Route::get('/aksi-konvergensi/create', [AksiKonvergensiController::class, 'create'])->name('aksi_konvergensi.create');
        Route::post('/aksi-konvergensi', [AksiKonvergensiController::class, 'store'])->name('aksi_konvergensi.store');
        Route::get('/aksi-konvergensi/{id}/edit', [AksiKonvergensiController::class, 'edit'])->name('aksi_konvergensi.edit');
        Route::put('/aksi-konvergensi/{id}', [AksiKonvergensiController::class, 'update'])->name('aksi_konvergensi.update');
        Route::delete('/aksi-konvergensi/{id}', [AksiKonvergensiController::class, 'destroy'])->name('aksi_konvergensi.destroy');
        Route::get('/peta-geospasial', [PetaGeospasialController::class, 'index'])->name('peta_geospasial.index');
        Route::get('/peta-geospasial/create', [PetaGeospasialController::class, 'create'])->name('peta_geospasial.create');
        Route::post('/peta-geospasial', [PetaGeospasialController::class, 'store'])->name('peta_geospasial.store');
        Route::get('/peta-geospasial/{id}/edit', [PetaGeospasialController::class, 'edit'])->name('peta_geospasial.edit');
        Route::put('/peta-geospasial/{id}', [PetaGeospasialController::class, 'update'])->name('peta_geospasial.update');
        Route::delete('/peta-geospasial/{id}', [PetaGeospasialController::class, 'destroy'])->name('peta_geospasial.destroy');
        Route::get('/pendamping-keluarga', [PendampingKeluargaController::class, 'index'])->name('pendamping_keluarga.index');
        Route::get('/pendamping-keluarga/create', [PendampingKeluargaController::class, 'create'])->name('pendamping_keluarga.create');
        Route::post('/pendamping-keluarga', [PendampingKeluargaController::class, 'store'])->name('pendamping_keluarga.store');
        Route::get('/pendamping-keluarga/{id}/edit', [PendampingKeluargaController::class, 'edit'])->name('pendamping_keluarga.edit');
        Route::put('/pendamping-keluarga/{id}', [PendampingKeluargaController::class, 'update'])->name('pendamping_keluarga.update');
        Route::delete('/pendamping-keluarga/{id}', [PendampingKeluargaController::class, 'destroy'])->name('pendamping_keluarga.destroy');
        Route::get('/carousel', [CarouselController::class, 'index'])->name('carousel.index');
        Route::get('/carousel/create', [CarouselController::class, 'create'])->name('carousel.create');
        Route::post('/carousel', [CarouselController::class, 'store'])->name('carousel.store');
        Route::get('/carousel/{id}/edit', [CarouselController::class, 'edit'])->name('carousel.edit');
        Route::put('/carousel/{id}', [CarouselController::class, 'update'])->name('carousel.update');
        Route::delete('/carousel/{id}', [CarouselController::class, 'destroy'])->name('carousel.destroy');
        Route::get('/data-riset', [DataRisetController::class, 'index'])->name('data_riset.index');
        Route::get('/data-riset/create', [DataRisetController::class, 'create'])->name('data_riset.create');
        Route::post('/data-riset', [DataRisetController::class, 'store'])->name('data_riset.store');
        Route::get('/data-riset/{id}/edit', [DataRisetController::class, 'edit'])->name('data_riset.edit');
        Route::put('/data-riset/{id}', [DataRisetController::class, 'update'])->name('data_riset.update');
        Route::delete('/data-riset/{id}', [DataRisetController::class, 'destroy'])->name('data_riset.destroy');
        Route::post('/data-riset/refresh', [DataRisetController::class, 'refresh'])->name('data_riset.refresh');
        Route::get('/tentang-kami', [TentangKamiController::class, 'index'])->name('tentang_kami.index');
        Route::get('/tentang-kami/create', [TentangKamiController::class, 'create'])->name('tentang_kami.create');
        Route::post('/tentang-kami', [TentangKamiController::class, 'store'])->name('tentang_kami.store');
        Route::get('/tentang-kami/edit', [TentangKamiController::class, 'edit'])->name('tentang_kami.edit');
        Route::put('/tentang-kami', [TentangKamiController::class, 'update'])->name('tentang_kami.update');
        Route::get('/layanan-kami', [LayananKamiController::class, 'index'])->name('layanan_kami.index');
        Route::get('/layanan-kami/create', [LayananKamiController::class, 'create'])->name('layanan_kami.create');
        Route::post('/layanan-kami', [LayananKamiController::class, 'store'])->name('layanan_kami.store');
        Route::get('/layanan-kami/{id}/edit', [LayananKamiController::class, 'edit'])->name('layanan_kami.edit');
        Route::put('/layanan-kami/{id}', [LayananKamiController::class, 'update'])->name('layanan_kami.update');
        Route::delete('/layanan-kami/{id}', [LayananKamiController::class, 'destroy'])->name('layanan_kami.destroy');
        Route::post('/layanan-kami/refresh', [LayananKamiController::class, 'refresh'])->name('layanan_kami.refresh');
        Route::get('/galeri-program', [GaleriProgramController::class, 'index'])->name('galeri_program.index');
        Route::get('/galeri-program/create', [GaleriProgramController::class, 'create'])->name('galeri_program.create');
        Route::post('/galeri-program', [GaleriProgramController::class, 'store'])->name('galeri_program.store');
        Route::get('/galeri-program/{id}/edit', [GaleriProgramController::class, 'edit'])->name('galeri_program.edit');
        Route::put('/galeri-program/{id}', [GaleriProgramController::class, 'update'])->name('galeri_program.update');
        Route::delete('/galeri-program/{id}', [GaleriProgramController::class, 'destroy'])->name('galeri_program.destroy');
        Route::post('/galeri-program/refresh', [GaleriProgramController::class, 'refresh'])->name('galeri_program.refresh');
        Route::get('/publikasi', [PublikasiController::class, 'index'])->name('publikasi.index');
        Route::get('/publikasi/create', [PublikasiController::class, 'create'])->name('publikasi.create');
        Route::post('/publikasi', [PublikasiController::class, 'store'])->name('publikasi.store');
        Route::get('/publikasi/{id}/edit', [PublikasiController::class, 'edit'])->name('publikasi.edit');
        Route::put('/publikasi/{id}', [PublikasiController::class, 'update'])->name('publikasi.update');
        Route::delete('/publikasi/{id}', [PublikasiController::class, 'destroy'])->name('publikasi.destroy');
        Route::post('/publikasi/refresh', [PublikasiController::class, 'refresh'])->name('publikasi.refresh');
        Route::get('/referensi', [ReferensiController::class, 'index'])->name('referensi.index');
        Route::get('/referensi/create', [ReferensiController::class, 'create'])->name('referensi.create');
        Route::post('/referensi', [ReferensiController::class, 'store'])->name('referensi.store');
        Route::get('/referensi/{id}/edit', [ReferensiController::class, 'edit'])->name('referensi.edit');
        Route::put('/referensi/{id}', [ReferensiController::class, 'update'])->name('referensi.update');
        Route::delete('/referensi/{id}', [ReferensiController::class, 'destroy'])->name('referensi.destroy');
        Route::post('/referensi/refresh', [ReferensiController::class, 'refresh'])->name('referensi.refresh');
        Route::get('/data-monitoring', [DataMonitoringController::class, 'index'])->name('data_monitoring.index');
        Route::get('/data-monitoring/create', [DataMonitoringController::class, 'create'])->name('data_monitoring.create');
        Route::post('/data-monitoring', [DataMonitoringController::class, 'store'])->name('data_monitoring.store');
        Route::get('/data-monitoring/{id}/edit', [DataMonitoringController::class, 'edit'])->name('data_monitoring.edit');
        Route::put('/data-monitoring/{id}', [DataMonitoringController::class, 'update'])->name('data_monitoring.update');
        Route::delete('/data-monitoring/{id}', [DataMonitoringController::class, 'destroy'])->name('data_monitoring.destroy');
        Route::post('/data-monitoring/refresh', [DataMonitoringController::class, 'refresh'])->name('data_monitoring.refresh');
        Route::get('/data-penduduk', [DataPendudukController::class, 'index'])->name('data_penduduk.index');
        Route::get('/data-penduduk/create', [DataPendudukController::class, 'create'])->name('data_penduduk.create');
        Route::post('/data-penduduk', [DataPendudukController::class, 'store'])->name('data_penduduk.store');
        Route::get('/data-penduduk/{id}/edit', [DataPendudukController::class, 'edit'])->name('data_penduduk.edit');
        Route::put('/data-penduduk/{id}', [DataPendudukController::class, 'update'])->name('data_penduduk.update');
        Route::delete('/data-penduduk/{id}', [DataPendudukController::class, 'destroy'])->name('data_penduduk.destroy');
        Route::post('/data-penduduk/refresh', [DataPendudukController::class, 'refresh'])->name('data_penduduk.refresh');
        Route::resource('balita', BalitaController::class);
        Route::post('balita/import', [BalitaController::class, 'import'])->name('balita.import');
        Route::get('balita/download-template', [BalitaController::class, 'downloadTemplate'])->name('balita.downloadTemplate');
        Route::resource('kartu_keluarga', KartuKeluargaController::class);
        Route::get('peta_geospasial', [PetaGeospasialController::class, 'index'])->name('peta_geospasial.index');
        Route::get('kelurahans/by-kecamatan/{kecamatan_id}', [KelurahanController::class, 'getByKecamatan'])->name('kelurahans.by-kecamatan');
        Route::resource('stunting', StuntingController::class);
        Route::get('/ibu', [IbuController::class, 'index'])->name('ibu.index');
        Route::get('/ibu/create', [IbuController::class, 'create'])->name('ibu.create');
        Route::post('/ibu', [IbuController::class, 'store'])->name('ibu.store');
        Route::get('/ibu/{id}/edit', [IbuController::class, 'edit'])->name('ibu.edit');
        Route::put('/ibu/{id}', [IbuController::class, 'update'])->name('ibu.update');
        Route::delete('/ibu/{id}', [IbuController::class, 'destroy'])->name('ibu.destroy');
    });
    Route::middleware('role:admin_kelurahan')->group(function () {
        Route::get('/admin-kelurahan/dashboard', function () {
            return view('admin_kelurahan.dashboard');
        })->name('admin_kelurahan.dashboard');
    });
    Route::middleware('role:perangkat_daerah')->group(function () {
        Route::get('/perangkat-daerah/dashboard', function () {
            return view('perangkat_daerah.dashboard');
        })->name('perangkat_daerah.dashboard');
    });
});